# Generated by Django 2.2 on 2020-10-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login', '0002_auto_20201027_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
