# Generated by Django 2.2 on 2020-10-28 09:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='question',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
