# Generated by Django 2.2 on 2020-10-29 03:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0004_auto_20201028_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='correct_ans',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
