# Generated by Django 2.2 on 2020-10-29 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0005_mcq_correct_ans'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MCQAnswer',
        ),
    ]
