# Generated by Django 2.2 on 2020-10-29 06:31

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online_exam', '0006_delete_mcqanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_answer', ckeditor.fields.RichTextField()),
                ('correct_answer', models.CharField(max_length=300, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_student', to=settings.AUTH_USER_MODEL)),
                ('test_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='std_test_question', to='online_exam.MCQ')),
            ],
        ),
    ]
