# Generated by Django 2.2 on 2020-10-30 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online_exam', '0007_studenttest'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentScoreDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
                ('test_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_question', to='online_exam.MCQ')),
            ],
        ),
    ]
