# Generated by Django 2.2 on 2020-10-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0008_studentscoredetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttest',
            name='score',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='StudentScoreDetail',
        ),
    ]
