# Generated by Django 2.2 on 2020-10-30 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online_exam', '0009_auto_20201030_0620'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0, null=True)),
                ('Rank', models.IntegerField(default=0, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_rank', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
